datasource:
  driver-class-name: "com.mysql.jdbc.Driver"
  url: "jdbc:mysql://52.78.44.33:3306/testdb?useUnicode=true&charaterEncoding=utf-8"
  user-name: "eastflag"
  password: "dklee98"
  initial-size: 10
  max-active: 100
  max-idle: 10
  min-idle: 10
  max-wait: 3000
  validationQuery: "SELECT 1"
  validationInterval: 36000
  testOnBorrow: "true"